# Generated by Django 5.2.3 on 2025-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_pay',
            field=models.BooleanField(default=False),
        ),
    ]
